### ISSUE TITLE
Add capability to "ignore" policy check 

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#616] opened 2023-10-26 12:08 UTC
# 💡 Summary #

What is the work, as a high-level summary?

Add capability to Scuba Config to explicitly ignore checking a given policy.  

## Motivation and context ##

Why does this work belong in this project?

This would be useful because user will have more flexibility to manage risks. 

## Implementation notes ##

Please provide details for implementation, such as:

- Add ignore section for policies 
- Allow justification for ignoring
- Allow expiration date for ignoring a policy
- Report Ignore policy info in Output report

## Acceptance criteria ##

How do we know when this work is done?

- [ ] User can choose to ignore a given policy
- [ ] Ignored policies reported with associated data

**Comment by mitchelbaker-cisa** [comment] 2024-06-18 00:02
Closing as this is a duplicate of #738 which is in progress.

**Closed by mitchelbaker-cisa** 2024-06-18 00:02 UTC
Labels: enhancement

**Comment by adhilto** [comment] 2024-06-18 15:36
> Closing as this is a duplicate of #738 which is in progress.
> 
> @adhilto Should we consider adding a consolidated section for all toggled policies and/or expiration dates? Those were the two items in the implementation notes list not covered in the scope of #738.

Ooh intriguing ideas, I hadn't thought of that. Expiration dates would be a nice-to-have feature, but I'd like them to be optional, as you might want to toggle something off permanently. And I'll toy around with what a consolidated section might look like.
