### ISSUE TITLE
AAD Connection Error

### ISSUE THREAD

**Issue by mferke** [cisagov/ScubaGear#465] opened 2023-07-31 19:48 UTC
# 🐛 Summary #

I followed the GitHub steps to install the modules from ScubaGear-main. PowerShell gave an error about Microsoft.Graph.Authentication 1.28.0 not being catalog signed, while Microsoft.Graph.Authentication 2.1.0 was installed on my machine. Ran uninstall script, and then reran .\SetUp.ps1. Modules reinstalled successfully, though Microsoft.Graph.Authentication error persists.

Upon running Invoke-Scuba, I hit R a bunch of times to run the script. I am presented with an authentication error to AAD, OneDrive, and SharePoint. The error message reads: "Connect-Tenant: Error establishing a connection with [service]. The term 'Get-MgProfile' is not recognized as the name of a cmdlet, function, script file, or operable program..." 

The other three products run correctly and present the output document.

I confirmed I am authenticating as a GA user and that I am running the correct version of PowerShell.

1. Set-ExecutionPolicy unrestricted
2. Navigate to directory, run .\SetUp.ps1.
3. Presented error about 1.28.0 version of Microsoft.Graph.Authentication.
4. cd to \ScubeGear-main\PowerShell\ScubaGear, run Import-Module -Name .\ScubaGear.psd1
5. Press R a bunch of times to run scripts
6. Run Invoke-Scuba, press R a bunch of times to run scripts
7. Presented with errors about aad, ondrive, and sharepoint: "[product] will be omitted from the output because of failed authentication"

"Connect-Tenant: Error establishing a connection with [product]. The term Get-MgProfile is not recognized as the name of a cmdlet, function, script file, or operable program..."

Add any screenshots of the problem here.
![scuba1](https://github.com/cisagov/ScubaGear/assets/141068906/78ffeede-2cd7-4a39-a035-ab84bee7f05f)
![scuba2](https://github.com/cisagov/ScubaGear/assets/141068906/4a25c91d-d8cc-403a-ac3e-023c0241c684)

**Comment by gdasher** [comment] 2023-07-31 21:26
Can you provide information about the versions of Graph running on your machine?

`Get-Module -Name Microsoft.Graph.Authentication -ListAvailable`

My suspicion is that what is going on is that the tool currently requires a 1.x version of Graph Powershell, which SetUp.sh attempts to install and which the tool will attempt to load at runtime.  But that version of the graph module is signed (while later versions are).  The solution is likely to run

`Install-Module -Scope CurrentUser -Force -AllowClobber -SkipPublisherCheck Microsoft.Graph.Authetnication`

and possibly the same for other modules if the error repeats.  This would work until such time as we fix the code to work with 2.0 (#463), which is the proper long term solution.  We will discuss that issue and see about if we can address it.

**Comment by mferke** [comment] 2023-08-01 13:55
Good morning,

The cmdlet returns 2.1.0, 1.28.0, and 1.9.0 for my machine's versions of Micosoft.Graph.Authentication.

Mark

Mark Ferketish
Associate Consultant
Microsoft Security CyberOps Resilience Team
***@***.******@***.***>

[Microsoft Logo]

**Comment by gdasher** [comment] 2023-08-02 22:04
Thanks.  Yes, the issue is that 2.0 introduced signing and triggers behavior in Windows when a previous version is unsigned.

A workaround would be to remove the 2.1.0 version of graph modules if they are not being used.

The error you're seeing is due to a change in the 2.1 implementation of Graph powershell and how it handles "beta" cmdlets, which scubagear uses a small number of.  We will address it as promptly as we can in #463.  We have reproduced that its what happens when scubagear tries to run with the 2.1 version of graph.

**Comment by nanda-katikaneni** [comment] 2023-08-03 18:20
Related to #463

**Comment by tkol2022** [comment] 2023-12-14 02:45
@mferke Our latest code base on the main branch is anchored on the Graph 2.x modules and therefore the problems experienced in this issue should be taken care of now. I'm closing this issue and if you have problems with the new application, please let us know! Thanks for your reporting.

**Closed by tkol2022** 2023-12-14 02:45 UTC
Labels: bug, public-reported
