### ISSUE TITLE
ConvertFrom-Json : Invalid JSON primitive

### ISSUE THREAD

**Issue by chenzhengdong125** [cisagov/ScubaGear#150] opened 2023-02-13 10:14 UTC
# 🐛 Summary #

What's wrong? Please be specific.

when I try to run this 

**Invoke-SCuBA -ProductNames aad -OutPath C:\report**

I get the following error message 

**ConvertFrom-Json : Invalid JSON primitive: .**
**At**
**C:\Users\test\Desktop\ScubaGear-v0-2-1\ScubaGear-0.2.1\PowerShell\ScubaGear\Modules\CreateReport\CreateReport.psm1:46
char:44**
**+ $SettingsExport =  Get-Content $FileName | ConvertFrom-Json**
**+                                            ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException**
    **+ FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand**

any idea what could be the issue? I have checked the jason file and the format seems correct, thanks

**Comment by nanda-katikaneni** [comment] 2023-02-14 19:43
@chenzhengdong125 Thanks for opening the issue and bringing our attention to this error. From the error message, it is unclear what is causing the issue. If possible, can you please share the ProviderSettingsExport.json and TestResults.json files (after redacting any sensitive information from them). This can help us debug the issue further.

**Comment by jgault91** [comment] 2023-02-15 17:40
@chenzhengdong125 It is happening to me too. It seems it only errors out when running against AAD, all other modules running fine. 
[ProviderSettingsExport.txt](https://github.com/cisagov/ScubaGear/files/10745871/ProviderSettingsExport.txt)
[TestResults.txt](https://github.com/cisagov/ScubaGear/files/10745873/TestResults.txt)

**Comment by gdasher** [comment] 2023-02-21 19:42
@chenzhengdong125 can you confirm if you have a similar situation (no CAP policies)?  If not, can you provide redacted JSON and TestResults so we can investigate the cause?

**Comment by chenzhengdong125** [comment] 2023-02-22 00:00
> @chenzhengdong125 can you confirm if you have a similar situation (no CAP policies)? If not, can you provide redacted JSON and TestResults so we can investigate the cause?

Thanks, I don't have any CAP in azure, so it will be the same issue I guess

**Comment by gdasher** [comment] 2023-02-22 02:20
Great.  In that case, you can try the code at HEAD (by using [this link](https://github.com/cisagov/ScubaGear/archive/refs/heads/main.zip)) or wait a few weeks for the 0.3.0 release to come out that should have the fix for this issue.

We'll go ahead and close as a duplicate of #134

**Closed by gdasher** 2023-02-22 02:20 UTC
Labels: bug, need info, public-reported
