### ISSUE TITLE
Error authenticating MS Graph PowerShell: AADSTS50146

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#502] opened 2023-08-28 17:58 UTC
# 🐛 Summary #

This is a general Graph PowerShell error rather than a ScubaGear specific issue. While the AAD error code appears on search results, the solutions seem to be unrelated to this specific error.  Documenting this here. 

We are unable to authenticate to AAD and run ScubaGear due to this error.
```
Write-Error: Error establishing a connection with aad. AADSTS50146: This application is required to be configured with an
application-specific signing key. It is either not configured with one, or the key has expired or is not yet valid.
```

The tenant in question DOES NOT have the ["official"](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/482)  Microsoft Graph PowerShell application registered. Attempting to automatically register the application also results in this error.

## Extra Notes 
- This is affecting all `Connect-MgGraph` authentication calls to the tenant.
- Authenticating from different clients also yielded the same error. Same error from Windows 10/11, PowerShell 5.1 & 7 clients. 
- Something might have gone awry when registering a [custom application](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#use-delegated-access-with-a-custom-application-for-microsoft-graph-powershell) on the tenant. 
- Might be able to bypass the issue via authenticating through a [service principal](https://github.com/cisagov/ScubaGear#application-service-principal-permissions--setup)

## To reproduce ##

Unknown

## Expected behavior ##

Able to authenticate to tenant via MS Graph PowerShell.
The goal of this issue is to recreate the problem and find the solution to it.

**Comment by tkol2022** [comment] 2023-12-14 22:04
### Reviewed 12/14
Have we ever had more than one user encounter this specific problem? If not, or if the number of users that encountered this is very low (i.e. the problem is rare), I recommend converting this from a bug into a documentation issue for future reference and closing this.

**Closed as not planned** 2024-06-19 16:16 UTC
Labels: bug
