### ISSUE TITLE
Update `setup-regal` action to v1.0 to remove annotated warning

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#947] opened 2024-02-29 14:43 UTC
# 🐛 Summary #

The current `Unit / Run-OPA-Tests` workflow includes use of the GitHub marketplace action `StyraInc/setup-regal`.  However, the v0.2.0 version uses an outdated version of Node.js which causes GitHub to annotate any run with a warning to update.  Changing the workflow to the line `StyraInc/setup-regal@v1` will resolve this issue as v1.0 specifically bumped the Node.js version from 16 to 20 to prevent this warning.

## To reproduce ##

1. Go to GitHub Actions, select the `Run-OPA-Tests` action
1. Select any previous run of this action and note the annotation warning at the bottom

## Expected behavior ##

Expectation is that the run only annotates the results with useful and relevant information and uses a supported version of software.

## Any helpful log output or screenshots ##

Example annotation warning:
![Screenshot 2024-02-29 at 8 37 47 AM](https://github.com/cisagov/ScubaGear/assets/108814318/bc1a7c6a-08ba-4c5a-9ad0-9e3d9eaa2a54)

**Comment by crutchfield** [comment] 2024-02-29 14:48
Duplicate of #917 ?

**Closed as not planned** 2024-02-29 15:32 UTC
Labels: bug, upstream update
